version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: cirrusci/flutter:master

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run Flutter Analyzer
          command: |
            flutter packages get
            dartanalyzer --options analysis_options.yaml . --format -h
      - run:
          name: Run the application tests
          command: |
            flutter test --coverage
      - codecov/upload:
          file: coverage/lcov.info
